version: "3"

services:
  tracker_db:
    image: postgres
    container_name: db_main
    restart: always
    environment:
      POSTGRES_DB: "itrum_tracker_java"
      POSTGRES_USER: "itrumadmin"
      POSTGRES_PASSWORD: "aboba"
    ports:
      - "5432:5432"

  tracker_test_db:
    image: postgres
    container_name: db_test
    restart: always
    environment:
      POSTGRES_DB: "itrum_tracker_java_test"
      POSTGRES_USER: "itrumadmin"
      POSTGRES_PASSWORD: "aboba"
    ports:
      - "5433:5432"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672

    networks:
      - rabbitmq_net

  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - "2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://1.2.3.4:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:SASL_PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
    depends_on:
      - zookeeper
    volumes:
      - ./:/etc/kafka

  email-service:
    build: email-service/email-service-server
    ports:
      - "8085:8085"
    environment:
      - SPRING_MAIL_HOST=
      - SPRING_MAIL_PORT=
      - SPRING_MAIL_PROTOCOL=
      - SPRING_MAIL_USERNAME=
      - SPRING_MAIL_PASSWORD=
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq

  tracker:
    build: tracker/
    ports:
      - "8080:8080"

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://tracker_db:5432/itrum_tracker_java
      - SPRING_DATASOURCE_USERNAME=itrumadmin
      - SPRING_DATASOURCE_PASSWORD=aboba

      - SPRING_DATASOURCE_FOR_TEST_URL=jdbc:postgresql://tracker_test_db:5433/itrum_tracker_java_test
      - SPRING_DATASOURCE_FOR_TEST_USERNAME=itrumadmin
      - SPRING_DATASOURCE_FOR_TEST_PASSWORD=aboba

      - SPRING_RABBITMQ_HOST=rabbitmq

      - JWT_TOKEN_SECRET=jwtapp
      - JWT_TOKEN_EXPIRED=3600000000
    depends_on:
      - email-service
      - rabbitmq
      - tracker_db

networks:
  rabbitmq_net:
    driver: bridge


